### ISSUE TITLE
Trouble with authenticate 

### ISSUE THREAD

**Issue by sseredkin-vergendo** [OpenArCloud/oscp-spatial-content-discovery#18]
Hi! I have a trouble with auth0, when I try to deploy oscp-spatial-content-discovery on local machine for test goals. Is it possible to disable jwt auth, or may be there is a test token?

**Comment by jamesjackson** [comment]
Hi @sseredkin-vergendo ! For now you can just remove the auth middleware and add a dummy tenant. I've added code blocks with the needed changes in here (uncomment these blocks and comment out the corresponding ones above):

https://github.com/OpenArCloud/oscp-spatial-content-discovery/blob/master/src/router.ts
