### ISSUE TITLE
Content definition

### ISSUE THREAD

**Issue by michaelvogt** [OpenArCloud/oscp-spatial-content-discovery#19]
The current content record seems mostly targeted at content to load over a provided URL. 

It seems to me very likely, that actually loading content is much less done than content that gets generated on device. This concept is used on Augmented City platform as placeholders (or stickers). 

In practice, content is defined by type, and the client application (like AC tourist, sparcl) have predefined objects (built with 3D primitives) to display at the locations of the content. 

To make this concept more flexible, I propose to add an optional property called definition to the interface Content, that would accept a JSON object that defines a theme definition (color, icon, rotation, ...)

This also means, refs property needs to be optional.

**Comment by jamesjackson** [comment]
This sounds good. The `type` property of Content is intended to have a high-level type such as `2d-text`. The inclusion of `refs` should depend on this `type`. The `type` values have yet to be enumerated. It makes sense to have a new `definition` property for additional formatting.
